### ISSUE TITLE
Rule Request: SwiftFormat

### ISSUE THREAD

**Issue by wokalski** [realm/SwiftLint#1049]
Although `SwiftLint` and `SwiftFormat` are separate and it's possible to cover some formatting rules using `SwiftLint` I thought it would be useful to be able to provide a `SwiftFormat` spec and lint formatting according to that.

I'm not sure if it's a good idea from `SwiftFormat` implementation point of view, but maybe @nicklockwood could share his thoughts.

**Comment by jpsim** [comment]
What do you mean "a `SwiftFormat` spec"? According to https://github.com/nicklockwood/SwiftFormat/issues/75, SwiftFormat doesn't have configuration files.

**Comment by wokalski** [comment]
I mean options. Sorry for the confusion.

**Comment by marcelofabri** [comment]
Is there something we can do here? I'm not sure what's the outcome of this.

**Comment by nicklockwood** [comment]
I think the basic idea would be for SwiftLint to run SwiftFormat on the code (with SwiftFormat options specified in the SwiftLint config file), and then raise a warning if the output was changed - i.e. because that would mean that the developer had failed to run SwiftFormat with those same options prior to committing their code.

I don't know whether something like that would be considered in-scope for SwiftLint, or if it would be more appropriate for a tool like [Danger](https://github.com/danger).

**Comment by marcelofabri** [comment]
So I finally understand what's the idea 😅 

IMO this is out of the scope of SwiftLint, and could be better implemented:
1. As a Danger plugin
2. As an option in SwiftFormat (https://github.com/nicklockwood/SwiftFormat/issues/158)
3. As a script that runs SwiftFormat and checks the diff (reverting after)

What do you think, @jpsim?

**Comment by nicklockwood** [comment]
@marcelofabri I think that's completely reasonable :-)

**Comment by marcelofabri** [comment]
Closing it for now.
