### ISSUE TITLE
Rule request: Check used image literals

### ISSUE THREAD

**Issue by Ben305** [realm/SwiftLint#1231]
It would be great to have a rule that could check if an image for every image literal really exists in an asset catalog.

**Comment by marcelofabri** [comment]
This is tricky because it depends on finding the asset catalog and parsing it. My suggestion would be using something like [SwiftGen](https://github.com/AliSoftware/SwiftGen) to solve this problem instead (at least for now).

AFAIK, currently there's no rule that depends on files that aren't the one being linted, so that's something we'd to think as well.

**Comment by marcelofabri** [comment]
I'm closing this for now because I think it's outside the scope of SwiftLint.
