### ISSUE TITLE
Regex cache non thread-safe

### ISSUE THREAD

**Issue by vincentisambart** [realm/SwiftLint#1344]
When running SwiftLint on our code base, SwiftLint crashes pretty often.
I cannot send you our source code, but I was able to reproduce the problem even when running SwiftLint on its own source code from Xcode.

I'm running SwiftLint with the command line arguments `lint --no-cache`.

As it's a multi-threaded-related problem, it won't occur every time, but in Xcode's scheme settings, in the Diagnostic tabs, enable "Thread Sanitizer" and "Pause on issues" and the Thread Sanitizer should report the problem every time.

The problem is in `NSRegularExpression+SwiftLint.swift`. Even though multiple files are checked in parallel, the regex cache that all threads access is not multi-thread safe.

The best solution is probably one of the following:
- Do not cache compiled regular expressions.
- Make the regex cache thread-safe (for example using GCD).
- Make the cache thread-local (probably need the most work).

**Comment by jonah-williams** [comment]
Thanks for digging into this. I haven't confirmed the root cause but I believe my current project is seeing the same issue as our number of linted files has grown.

If it helps anyone spot instances of the same: I'm seeing swiftlint crash intermittently with `Segmentation fault: 11  "${SWIFT_LINT}" lint --path "${path}" --no-cache` which then surfaces in Xcode as a `Command /bin/sh failed with exit code 139` if you're running swiftlint as part of a run script build phase.

**Comment by jpsim** [comment]
Thanks for filing this. Should be a quick fix: #1347.

**Comment by vincentisambart** [comment]
Thanks for the quick fix.
