### ISSUE TITLE
How to identify error/warnings from swiftlint?

### ISSUE THREAD

**Issue by vidhyasri2106** [realm/SwiftLint#1610]
Is it possible to identify if the error/warning produced in the xcode after implementing swiftlint is xcode generated error or swiftlint generated error. I am doing CI-CD setup for my iOS application. After creating bot, xcode server shows all errors and warnings created using swiftlint in the xcode console. But i need to identify if the specific error is due to swiftlint or normal xcode error. Is there any way to do this?

**Comment by SDGGiesbrecht** [comment]
I can think of two ideas:

Method 1: Separate SwiftLint from the build in continuous integration.

The CI script would remove SwiftLint from the build phases of the Xcode project and run SwiftLint separately in a different portion of the script.

This is how [Workspace](https://github.com/SDGGiesbrecht/Workspace) does it. It has the side affect of allowing the CI to run SwiftLint with different flags than Xcode. In Workspace, Xcode continues building past warnings during development but CI uses `--strict` to turn everything into an error with a failing exit code. [Here are the parts of Workspace’s source that deal with disabling and re‐enabling the build phase.](https://github.com/SDGGiesbrecht/Workspace/blob/350a95b7784ed2f2ad59d831b12929735facdd05/Sources/WorkspaceLibrary/Refresh/Xcode/Xcode.swift#L164-L233) You can adapt that into your CI script, looking for `swiftlint lint` instead of `workspace proofread`.

Method 2: Assume—I do not know how safely—that SwiftLint’s output pattern is exclusive to SwiftLint and test each warning description against this pattern:

`Rule Name Violation: Description for humans. (rule_identifier)`

**Comment by marcelofabri** [comment]
Method 1 described by @SDGGiesbrecht could be even simpler: create a script that runs `swiftlint lint` if not on CI (using ENV vars to check) and run it on the build phase.

Then on CI you run `swiftlint lint` on a separate job so you can treat it.

**Comment by SDGGiesbrecht** [comment]
Yes, Marcelo is right, his way is far simpler for most CI arrangements.

I am trying to remember what prevented me from doing it that way... but I the reason escapes me now. It is probably time to revisit that decision.

**Comment by SDGGiesbrecht** [comment]
Thanks, @marcelofabri.
