### ISSUE TITLE
Swiftlint + Travis Linux

### ISSUE THREAD

**Issue by bolismauro** [realm/SwiftLint#1617]
Hi everyone,
I'd love to use swiftlint in a CI environment. The problem is that, if I use a macOS environment, the build time is gigantic.

I was thinking to use a linux environment instead and run swiftlint inside this environment.

Is this possible? Theoretically all the pieces run on Linux, but I'm wondering If I'm missing something

**Comment by marcelofabri** [comment]
This is possible, but you need to install SourceKit by yourself. There's a docker image provided by @norio-nomura which already has it installed: `norionomura/sourcekit:311`. 

Note that SwiftLint is slower on Linux (#1577) and some rules might behave different because Foundation is not the same one that is available on Darwin.

**Comment by bolismauro** [comment]
Interesting, thanks!

**Comment by marcelofabri** [comment]
I'm closing this, feel free to reopen or create another issue if you have more questions!
