### ISSUE TITLE
Clear cache when used toolchain changes

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#1709]
We probably should store the Swift toolchain used for running SwiftLint and clear the cache when it changes.

More information on how SwiftLint deals with multiple Swift versions: https://github.com/realm/SwiftLint#working-with-multiple-swift-versions

**Comment by jpsim** [comment]
You're technically right, but I think this can be super low priority, because the only time this should matter is when both the following conditions are met:

1. No changes are required to your source code to compile across both toolchain versions; and
2. The different toolchains would produce different (valid) violations

I think in practice it's very unlikely that both these conditions will be met simultaneously.

**Comment by marcelofabri** [comment]
Agreed.

**Comment by jpsim** [comment]
As highlighted by #1741, this can be hit more easily than I had originally assumed.

**Comment by marcelofabri** [comment]
Is there a way to know which toolchain SourceKitten is using? Or would this require some changes there as well?

**Comment by jpsim** [comment]
There's no way currently to do that, no 😞

Exposing these declarations/types publicly would be sufficient, but a terrible way, to expose that to SwiftLint:

https://github.com/jpsim/SourceKitten/blob/0.18.0/Source/SourceKittenFramework/library_wrapper_sourcekitd.swift#L9
and
https://github.com/jpsim/SourceKitten/blob/0.18.0/Source/SourceKittenFramework/library_wrapper.swift#L12

**Comment by marcelofabri** [comment]
@jpsim But that actually may not be enough. For example, if someone updates Xcode, the toolchain path will be the same, won't it?
