### ISSUE TITLE
Segmentation Fault in SwiftLint 0.3.0

### ISSUE THREAD

**Issue by kmikael** [realm/SwiftLint#188]
I upgraded my homebrew-installed SwiftLint to Version 0.3.0 and now I only get a segmentation fault whenever I run `swiftlint`.

`swiftlint help` works still but any other command exits with exit code 139 and prints `zsh: segmentation fault  swiftlint` to the console.

**Comment by diogoguimaraes** [comment]
+1

**Comment by diogoguimaraes** [comment]
Fixed it performing the following steps:
* `brew uninstall swiftlint`
* Delete the swiftlint framework manually from /Library/Frameworks
* `brew install swiftlint` (You may have to force the symbolic links with `brew link --overwrite swiftlint` afterwards)
* Restart Xcode

**Comment by kmikael** [comment]
This worked for me too, thanks.

Why did SwiftLint install something in my `/Library/Frameworks` folder?

**Comment by jpsim** [comment]
> Why did SwiftLint install something in my `/Library/Frameworks` folder?

Usually, I'd build CLI binaries statically linking all its dependencies so that it's a self-contained binary, but Swift frameworks can't be statically linked, so we have to install the dynamic frameworks in a separate location. This unfortunately leads to many headaches when there are frameworks available in rpath locations that SwiftLint doesn't expect.

**Comment by jpsim** [comment]
If anyone else hits this issue, please follow the steps listed above in https://github.com/realm/SwiftLint/issues/188#issuecomment-154437739.
