### ISSUE TITLE
Use SwiftSyntax from Swift 4.1?

### ISSUE THREAD

**Issue by SiarheiFedartsou** [realm/SwiftLint#1972]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Rule Request

Did someone take a look at https://github.com/omochi/SwiftSyntax/tree/master/Sources/SwiftSyntax ? As I understand it is a new API for parsing Swift code. I think, it will give ability to SwiftLint to "understand" Swift code structure(not only classes, functions and methods) and do linting in more accurate way.

**Comment by SDGGiesbrecht** [comment]
Very interesting.

For now, however, the library itself recommends against using it yet. From [apple/swift/lib/Syntax](https://github.com/apple/swift/tree/master/lib/Syntax#swift-syntax-and-structured-editing-library),

> This library is a work in progress and should be expected to be in a molten state for some time. Don[’]t integrate this into other areas of the compiler or use it for anything serious just now.

It also says,

> Eventually, the goal of this library is to represent Swift syntax in all of the compiler.

It sounds like when (Swift‐)Syntax is ready, SourceKit ([apple/swift/tools/SourceKit](https://github.com/apple/swift/tree/94d0e4e7a1675c13cfc1a7637067dd0175006c4d/tools/SourceKit)) itself will be powered by it. SwiftSyntax may enable more fine‐grained queries, but whatever “understanding” it has gets inherited by the higher‐level SourceKit. Since it is on SourceKit that SwiftLint is built even now, resulting improvements will be inherited for free.

Still very much worth watching to see how SwiftSyntax evolves. Thanks for the tip @SiarheiFedartsou!

**Comment by marcelofabri** [comment]
@SDGGiesbrecht Just to complement: nothing everything is exposed by SourceKit to us. I've been doing [some PRs](https://github.com/apple/swift/pulls?utf8=✓&q=sourcekit++author%3Amarcelofabri+) to it to add more information that could be helpful to us, but SwiftSyntax would be much more powerful and provide more details.

One downside though is that (from my understanding) we would need to link against a specific version of it, instead of "finding it", as [we do with SourceKit](https://github.com/realm/SwiftLint#working-with-multiple-swift-versions). This means  that a certain version of SwiftLint would only reliably work with the Swift version from which SwiftSyntax was used.

IMO SwiftSyntax would be the way to go in the future, but it looks like too immature right now. I'd love to see some proofs of concept though on how would it be to use it in a SwiftLint context.

**Comment by SDGGiesbrecht** [comment]
SwiftSyntax will probably be [locatable](https://github.com/apple/swift/tree/0782b482b364f15741cc4a445976d8167c1a9d25/lib/Syntax#try-libsyntax-in-xcode) alongside SourceKit.

(As opposed to using the extracted package linked from the first comment, which *would* involve the drawbacks you mentioned, @marcelofabri.)

There is just nothing to locate without Swift 4.1.

**Comment by jpsim** [comment]
Worth noting too that SourceKit provides the structure from a later point after the parser, which means that it can sometimes disambiguate what the parser thought it saw. So moving entirely to SwiftSyntax, even when it's been completed, might still not be sufficient for all our existing rules.

**Comment by SDGGiesbrecht** [comment]
SwiftSyntax was not released with Swift 4.1. Next release maybe?

**Comment by MaxDesiatov** [comment]
Any updates on this? Seems like blocking performance issues in SwiftSyntax were fixed with the release of Swift 5.1

**Comment by jpsim** [comment]
@MaxDesiatov would you be interested in refreshing https://github.com/realm/SwiftLint/pull/2476 to see how it performs with Swift 5.1.3? Some updated performance numbers could help assess the viability of using SwiftSyntax.

**Comment by marcelofabri** [comment]
Using SwiftSyntax is now possible after https://github.com/realm/SwiftLint/pull/3054. I recommend using it only for opt-in rules for now, at least until Swift 5.2 is released, which will contain a few speed optimizations (https://github.com/apple/swift-syntax/pull/155 and https://github.com/apple/swift-syntax/pull/158)
