### ISSUE TITLE
Increase access level of Commands

### ISSUE THREAD

**Issue by nhgrif** [realm/SwiftLint#2107]
I am working with a team trying to develop a tool that does some code analysis on iOS projects.  We have integrated SwiftLint as part of this tool, however currently we are limited to running SwiftLint from the command line.  This poses several problems for us.

We'd like to include SwiftLint directly as a dependency of our project, however unfortunately nothing is marked public.

What would the appetite be for marking some parts of SwiftLint as `public` so it can be directly incorporated into other tools?

**Comment by marcelofabri** [comment]
@nhgrif The recommendation for clients would be to use only `SwiftLintFramework`, which should expose all functionality needed to lint files. That's what we use in [IntegrationTests.swift](https://github.com/realm/SwiftLint/blob/master/Tests/SwiftLintFrameworkTests/IntegrationTests.swift).

**Comment by SDGGiesbrecht** [comment]
@nhgrif, the Swift API is entirely undocumented (correct me if I am wrong, @marcelofabri). But you could run [Jazzy](https://github.com/realm/jazzy) on `SwiftLintFramework` to get an idea of what entry points are public.

However, when I did something similar myself, I ended up [not going that route](https://github.com/realm/SwiftLint/issues/1324) because of how much is actually implemented in the executable tool. Instead I [used the command line interface from within Swift](https://github.com/SDGGiesbrecht/Workspace/blob/dc4af8fa3f8979c469560caaa525427682a67741/Sources/WorkspaceLibrary/External%20Tools/Third%20Party/SwiftLint.swift#L20-L83). Maybe something that would also work for you.

**Comment by marcelofabri** [comment]
I wouldn't say entirely undocumented, but yeah, we should do a better job there.

**Comment by nhgrif** [comment]
@SDGGiesbrecht we actually already have that functioning, however we quickly ran into trouble on our build servers.

See, we haven't been keeping SwiftLint up to date on our build machines, because we migrated all of our iOS projects over to pulling SwiftLint in as a pod, so they can all specify their own version of SwiftLint and so we don't have to worry about updating our build servers.

```
    func createSwiftlintReport() throws -> String {

        return try shellOut(
            to: Command.swiftlint.rawValue,
            arguments: [
            "lint",
            "--benchmark"
            ])
    }
```

We'd just like Swiftlint to be integrated directly.  

@marcelofabri If I have some time today, I may play around with Jazzy.  Can the docs be hosted similarly to how Metova hosts docs for our libraries?  For example: http://metova.github.io/MetovaTestKit/

**Comment by nhgrif** [comment]
[docs.zip](https://github.com/realm/SwiftLint/files/1841680/docs.zip)

**Comment by SDGGiesbrecht** [comment]
@nhgrif

> @SDGGiesbrecht we actually already have that functioning, however we quickly ran into trouble on our build servers.

What I meant was more along the lines of one of the following:
- with the package manager, you could specify the SwiftLint executable as a package dependency and it will be built alongside your packager in the same build directory. Its relative location is predictable, so you can launch the particular executable directly. (You can still call the executable with its fully qualified path through the shell, but you could also just point `Process.launchPath` at SwiftLint and bypass the shell entirely.)
- if your product is an application bundle, you can build SwiftLint with Xcode and include the executable in your application bundle, running the bundled executable the same way.
- like the example I linked above, you can make your tool so that if the wrong version of SwiftLint is installed, then the tool attempts to download the right version for its own cache and runs that version. (You would have to look at the superclasses to see all of what is going on.)

But if you do find what you need in Jazzy’s output, go ahead and use `SwiftLintFramework`.
