### ISSUE TITLE
What is --format for

### ISSUE THREAD

**Issue by danlozano** [realm/SwiftLint#2368]
What is the difference between calling `swiftlint autocorrect` and `swiftlint autocorrect --format`?

I can't seem to find it anywhere in the readme or documentation or code.

Thanks =)

**Comment by marcelofabri** [comment]
`--format` also reformats the file as Xcode would with CTRL + I.

**Comment by danlozano** [comment]
Oh, so it's just autocorrecting the rules that can be autocorrected, and then tacking on a CTRL + I at the end?

Interesting, thanks! Was beating my head against a wall trying to find this somewhere.

So, if I want to CTRL + I my whole project I can just run autocorrect --format ? Cool. Was looking to do this because of some issues with tabs/spaces.

**Comment by ornithocoder** [comment]
@marcelofabri, do you remember, off the top of head, what's the order SwiftLint applies the changes?

1. format + autocorrect, or
1. autocorrect + format

I'm asking this because I'm facing an issue here. When I use `swiftlint autocorrect --format` it format all my files, but reverts the changes made by the Corrected Closure End Indentation Rule. After running I have to run `swiftlint autocorrect` to fix the Corrected Closure End Indentation Rule again.

**Comment by marcelofabri** [comment]
It first apply the corrections and then format:

https://github.com/realm/SwiftLint/blob/523feaeffad4ddc3cda845f9da7bae16f2bf9cf8/Source/swiftlint/Commands/AutoCorrectCommand.swift#L35-L42

**Comment by ornithocoder** [comment]
@marcelofabri, is that the expected behavior? What if the a rule conflicts with the format applied?
