### ISSUE TITLE
Wrong "second self" force unwrapping violation

### ISSUE THREAD

**Issue by janmisar** [realm/SwiftLint#2779]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

```swift
button.on { [weak self] _ in
    self?.delegate?.didTapClose(in: self!)
}
```
This creates force unwrapping warning and it should not. This is safe - when self is nil, second self is not even called so it won't crash.

It used to work great in previous versions. It's broken since 0.33, I guess it could be connected with #2759.

**Comment by jpsim** [comment]
> This creates force unwrapping warning and it should not. This is safe - when self is nil, second self is not even called so it won't crash.

Are you sure this is safe? What if the last reference to `self` is released by a different thread between the time the left `self` is evaluated and the right `self!` is evaluated?

> It used to work great in previous versions. It's broken since 0.33, I guess it could be connected with #2759.

You have this backwards, a limitation in SwiftLint meant that the `force_unwrapping` rule wasn't applied to `self` keywords at all. The behavior you're describing has also applied to identifiers other than `self` since the rule was originally created: `controller?.delegate?.didTapClose(in: controller!)`
