### ISSUE TITLE
Autocorrect colon violations

### ISSUE THREAD

**Issue by brennantaylor** [realm/SwiftLint#331]
Would it be possible? I wouldn't mind giving it a shot.

**Comment by jpsim** [comment]
`ColonRule` violations can already be automatically corrected: https://github.com/realm/SwiftLint/blob/d9a885e5b5d8876bd0bcd52dc908f77acd8e6bf5/Source/SwiftLintFramework/Rules/ColonRule.swift#L53-L76

This was done in #283, which has been available since SwiftLint 0.5.3.

Are there cases that aren't currently covered?

**Comment by brennantaylor** [comment]
You are correct. I updated to 0.5.4 (brew's latest version) and it did correct the colons. Closing this.
