### ISSUE TITLE
SwiftLint could use a CODEOWNERS file

### ISSUE THREAD

**Issue by sethfri** [realm/SwiftLint#3357]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

For someone contributing to SwiftLint for the first time, it's not obvious who needs to review your code, or who to follow up with if your PR still hasn't been reviewed. GitHub has a solution for this in the form of a [`CODEOWNERS` file](https://github.blog/2017-07-06-introducing-code-owners/). This would allow reviews to automatically be requested once PRs are moved out of the draft state. You can even add different owners for different sections of the codebase if folks have more expertise in one area or another.

I'd be more than happy to add this, but I'm not sure who would be best. Using this issue to kick off a conversation!

**Comment by jpsim** [comment]
Thanks for the suggestion, Seth!

Unfortunately, a CODEOWNERS file wouldn't solve the problem of SwiftLint being maintained by a group of volunteers with varying amounts of free time available to review PRs.

Some maintainers are more active for a few weeks/months then drop off due to lack of time, then come back again a few months later.

I aimed to decentralise maintainership as much as possible over the years, granting push access to many people who showed an interest and an ability to contribute to SwiftLint, [documenting how to cut releases](https://github.com/realm/SwiftLint/blob/master/Releasing.md), etc.

I realise this isn't super encouraging to hear when your PR has been sitting unreviewed for a long time.

**Comment by sethfri** [comment]
That totally makes sense, thanks for the context! 

Do you think it might still be valuable to notify certain maintainers that areas of the codebase they have expertise in are being touched? That way, they know they can drop in on those if they have time instead of digging through the backlog of PRs, which could feel overwhelming if you're just getting back into SwiftLint after a few months off. As long as the repo doesn't enable required reviews, they won't be obliged to review before the PR is merged; it would act as more of an fyi.

Lmk what you think!

**Comment by jpsim** [comment]
I think the big risk there is that some people start contributing, they're eager to help, and then after a few months they never come back to the project. I've seen that happen a lot, and I'm concerned that an owners file might give a false sense of hope that a specific person is going to engage with an issue or PR.

**Comment by sethfri** [comment]
That makes sense to me. Thanks for considering it!
