### ISSUE TITLE
[Feature] Get the category of a rule

### ISSUE THREAD

**Issue by derLalla** [realm/SwiftLint#3454]
I want to know if there is a way to dynamically tell to which category a rule belongs?  
E.g. trailing_semicolon belongs to idiomatic.  

Until now we are using a rating system based on categories to grade our students code. In Java we are using checkstyle, spotbugs, etc. to get a static code analysis and map the resulting issues to categories.  

Now it would be nice to have such a feature when using SwiftLint. What I can think of right now is to manually write a Map which groups all rules into its own category. Then if I get to find the rule `trailing_semicolon` it can be mapped to `idiomatic`.

It would be great, if the reporter could do this step and integrate the category into the resulting output.

**Comment by agarmash** [comment]
Sure, it can be done by storing `RuleKind` value in `StyleViolation` struct and adding it into the output data of the desired reporter.  
I'm not sure if it should be added to the public version of SwiftLint, however, it's always possible to build your own modified version. I can make a patch for you, but I need to know which reporter you are going to use (Xcode reporter, JSON reporter, HTML reporter, etc)

**Comment by derLalla** [comment]
I think it might be useful to others as well, as to have more information is not really harmful.  
I am using the checkstyle reporter. And instead of creating a new tag for the Checkstyle.xml (in my case), you could add the RuleKind to the source, like it is done in Java:  

swiftlint.rules.trailing_semicolon -> swiftlint.rules.idiomatic.trailing_semicolon

**Comment by agarmash** [comment]
The problem with modifying the existing report structure is that it will break lots of existing configurations, and we want to avoid it.  

Adding fields is another story, but it still has to be discussed with maintainers. For example, adding something to the Xcode reporter output seems like a bad idea since a) it's better to keep the lines short so they fit in the editor aside from the violating line of code without being truncated, b) people are used to the existing report messages format.  

Of course, it's possible to implement additional parameters in the config file for alternating the format of reports, but it doesn't look like a thing that a lot of people are probably going to use. However, if my assumption is wrong, let me know!

As for your feature request, I'll make a patch for you that will add the rule kind to the Checkstyle report 🙂

**Comment by agarmash** [comment]
Here's an archive with the patch that adds rule kind to the reporter output as you suggested, like `source="swiftlint.rules.metrics.line_length"`, and compiled binary for macOS.  

If you want to build a binary yourself (e.g. to build one for the Linux or to build an updated version), apply the patch to the sources and build the binary with `make` using one of the commands from the `Makefile`. 
For example, `make portable_zip` will build the binary for macOS, while `make zip_linux` will build the one for Linux. 

Feel free to ask if you have any difficulties

[checkstyle_reporter_rule_kind.zip](https://github.com/realm/SwiftLint/files/5658117/checkstyle_reporter_rule_kind.zip)

**Comment by derLalla** [comment]
Hey thanks! I don't get the part with creating my own binary though.. But I can use the .diff and just apply it to my cloned branch, right?  
Now comes the tricky part. I am installing SwiftLint in my docker container by cloning from master and then compile it with 'swift build --configuration release -Xswiftc -static-stdlib'. An official release would of course be easier and to maintain my own fork would take continuous manual effort.  
Do you know a good way of incorporating your .diff into my docker container?

**Comment by agarmash** [comment]
You are welcome!
Sure, in your case just apply the patch with `git apply` after cloning the branch and before compiling.  

Can't say anything regarding Docker since I haven't used it in my practice.
