### ISSUE TITLE
Move explicit_self from analyzer rule to an opt-in rule?

### ISSUE THREAD

**Issue by cprovatas** [realm/SwiftLint#3526]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Are there any plans to do this?  Would be great if we can run all rules in one invocation without requiring the setup / configuration work needed to get the `swiftlint analyze` command to work properly on various different machines / environments.

**Comment by jpsim** [comment]
SwiftLint’s analyzer rules work very differently from its lint rules. The analyzer rules operate on the post-typechecked AST, which is why exact compiler arguments for all files being analyzed are needed. Lint rules on the other hand operate on the pre-typechecked AST, which doesn’t need compiler arguments at all, and tend to be way faster.

**Comment by cprovatas** [comment]
And I suppose this means that porting the explicit_self rule to using a pre-typechecked AST would be impossible / infeasible at the moment.  Is this accurate?

**Comment by jpsim** [comment]
Correct

**Comment by cprovatas** [comment]
Thanks!
