### ISSUE TITLE
Xcode cannot resolve package dependencies for Swift Package project with version 0.50.0

### ISSUE THREAD

**Issue by engineeric** [realm/SwiftLint#4558]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When trying to use SwiftLint 0.50.0 in a Swift Package project, Xcode 14.1 fails to resolve dependencies because SwiftLint is dependent on an unstable version of SwiftSyntax.

### Environment

* SwiftLint version 0.50.0
* Xcode 14.1
* Swift Package Manager

```swift
.package(url: "https://github.com/realm/SwiftLint.git", from: "0.50.0")
```

Error: "Failed to resolve dependencies Dependencies could not be resolved because root depends on 'swiftlint' 0.50.0..<1.0.0.
'swiftlint' >= 0.50.0 cannot be used because no versions of 'swiftlint' match the requirement 0.50.1..<1.0.0 and package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax'."

**Comment by jpsim** [comment]
How is it unstable when it’s pinned to a specific commit?

**Comment by engineeric** [comment]
Apple shenanigans 🤷

**Comment by jpsim** [comment]
I was able to cut a tagged release for SourceKitten and am updating that here: https://github.com/realm/SwiftLint/pull/4569

However, I'm still trying to find a good way to solve this for SwiftSyntax. I think I'll need to depend on tags rather than commits. Tags are published fairly regularly and I think SwiftPM would be satisfied with the "stability" of tags over commits: https://github.com/apple/swift-syntax/tags

**Comment by jpsim** [comment]
I think you can work around this by pinning to an exact version of SwiftLint:

```swift
.package(url: "https://github.com/realm/SwiftLint.git", revision: "0.50.0"),
```

So instead of `from:` use `revision:`.

**Comment by designatednerd** [comment]
> How is it unstable when it’s pinned to a specific commit?

I also was not expecting "But I literally pointed at one specific commit how the hell is that unstable", but it appears in SPM's definition, it is. I can't remember if it just has to be a published tag or if it also has to be a semver compliant tag, but it's at least got to be a tag.

**Comment by jpsim** [comment]
I'm going to close this issue, and won't switch to swift-syntax tags unless there's a reason someone can't use `revision:` for some reason.

**Comment by designatednerd** [comment]
@jpsim FWIW: I can't use revision because I'm using it on several internal libraries, which then means anything that imports those libraries has to use revision, because it then has a dependency on SwiftLint, which is unstable. 

This also goes for any OSS lib that wants to use SwiftLint via SPM. I don't think leaving it at "just point to a specific revision" is going to be a long term workable solution. 

LMK if I can help twist some arms to get a release cut somewhere.

**Comment by jpsim** [comment]
Ok, thanks for sharing that. Another way we could do this is to use the binary releases of SwiftLint but then that might mean not supporting Linux. But then the plugin would have no dependencies (in the SwiftPM sense of the term).

**Comment by andyj-at-aspin** [comment]
As with the original poster, I have SwiftLint referenced by a sub-package in my projects just so a build script can do a command-line swift build of it before running a lint over the entire project. This is so my CI/CD servers always get the required version of SwiftLint and report all warnings during analysis actions without needing user intervention to go and ensure the CI/CD server has the necessary version of SwiftLine already installed on it.

As the package file exists in my project workspaces, Xcode detects it and adds it to the workspace's Package.resolved. Because SwiftLint is now using a non-Tag reference to SwiftSyntax it's considered unstable by Xcode, making my complete Package.resolved unstable and preventing projects from building for release. I am now faced with either removing SwiftLint from my project workflows entirely, sticking at the last version considered stable by SPM - 0.49.1 or losing all automation and having to obtain and update SwiftLint on all development and CI/CD hardware manually.

I'd be really grateful if some way around this was found. As far as the SwiftSyntax folk seem concerned you've been tracking their pre-release bleeding edge for a while, going by the frequency of alterations to SwiftLint's Package.swift - but then maybe you managed to automate that.

**Comment by jpsim** [comment]
Possibly one way to work around this would be for me to fork SwiftSyntax and cut semver release tags there.

I really dislike the lack of flexibility of SwiftPM at the moment.

**Comment by andyj-at-aspin** [comment]
I'm sure I wouldn't be the only one who'd be very grateful if that happened. I know I could do it myself, but only by forking BOTH SwiftSyntax and SwiftLint - and that's just a shame.

I'm also vaguely frustrated by SPM - having committed to only using SPM and not CocoaPods, Carthage etc. - to the point when I'm already forking Gwendal Roué's GRDB just so I can switch on support for SQLite's FTS5 functionality by adding an extra Swift build flag into it's dependencies.

**Comment by pchmelar** [comment]
Also, it seems that an exact version can't be used when adding SwiftLint directly to the Xcode project. 😕 

<img width="1101" alt="Screenshot 2022-11-28 at 9 56 09" src="https://user-images.githubusercontent.com/3842139/204236140-1e97ced3-5ae4-40f4-9a37-fa49b2f1cff4.png">

```
Failed to resolve dependencies Dependencies could not be resolved because package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax' and root depends on 'swiftlint' 0.50.1.
```

**Comment by tonyarnold** [comment]
Yeah, I hit this too. I was able to workaround the issue by specifying an unstable version of SwiftLint (I used `branch: "main"`).

**Comment by jpsim** [comment]
My plan is to switch the plugin to use a pre-built binary for macOS, I just haven’t gotten around to doing that yet.

If someone wants to make a PR in the meantime, that’s cool too.

**Comment by tonyarnold** [comment]
@jpsim similar to this? #4603

**Comment by jpsim** [comment]
Switched to a prebuilt binary for macOS in #4603

**Comment by andyj-at-aspin** [comment]
> Switched to a prebuilt binary for macOS in #4603

Can I just register my thanks to all involved in resolving this. I realise a new witty clothes drying pun will have to occur (yes I've glanced at releasing,md and can't work out if the reference to https://github.com/realm/SwiftLint/releases/new in it is broken) but know that I am already grateful regardless.

**Comment by jpsim** [comment]
Only project maintainers can create new releases, which is why https://github.com/realm/SwiftLint/releases/new doesn't work for you.

**Comment by 1024jp** [comment]
According to my trials, you can also use SwiftLint on Xcode by specifying a commit.

<img width="490" alt="Screenshot 2022-12-01 at 10 32 52" src="https://user-images.githubusercontent.com/1165044/204944389-4fcc6d73-70f8-48db-a9f5-14c65d25d60b.png">
