### ISSUE TITLE
SwiftLint Run Script Phase fails on Xcode 15

### ISSUE THREAD

**Issue by inTheAM** [realm/SwiftLint#5130]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
Using SwiftLint on Xcode 15 Beta causes an error:
"Command PhaseScriptExecution failed with a nonzero exit code"

### Environment

- SwiftLint version 0.52.4

- Installation method used: Homebrew

- Paste your configuration file: None

- Are you using nested configurations: No

- Which Xcode version are you using: Xcode 15.0 Beta 3, Build version 15A5195k

**Comment by lucaszischka** [comment]
Issue remains on **Xcode Beta 6**:

> Linting Swift files in current working directory
> Error: No lintable files found at paths: ''
> Command PhaseScriptExecution failed with a nonzero exit code

- Installation method: pre-built package
- Version: 0.52.4

**Comment by AlexHadfield** [comment]
It was working for me up to Xcode 15 Beta 7, but on Beta 8 it stopped working.

**Comment by kmaschke85** [comment]
Still the case with Xcode beta 8 and SwiftLint 0.52.4

**Comment by kmaschke85** [comment]
I guess it is related to #5053

**Comment by v1adisLuvv** [comment]
Possible solution found:

In Xcode 14, Apple aded a new flag [ENABLE_USER_SCRIPT_SANDBOXING](https://developer.apple.com/documentation/xcode/build-settings-reference#User-Script-Sandboxing) that tells the build system whether to block scripts phases from accessing source files or intermediate build objects.
Back in Xcode 14 (by default) this flag was set to NO, so everything was working fine. But in Xcode 15 this flag is now set to YES, and the script cannot access files.
Fortunately the workaround to this issue is simple:
Open project settings.
Open your target.
Select Build Settings.
Search for ENABLE_USER_SCRIPT_SANDBOXING.
Change the User Script Sandboxing to NO.

**Comment by v1adisLuvv** [comment]
Possible solution:

In Xcode 14, Apple added a new flag [ENABLE_USER_SCRIPT_SANDBOXING] that was set to NO by default. But in Xcode 15 is now set to YES. Change it back to NO.

More details in the source: 
https://thisdevbrain.com/swiftlint-permission-issue/

**Comment by SimplyDanny** [comment]
> In Xcode 14, Apple added a new flag [ENABLE_USER_SCRIPT_SANDBOXING] that was set to NO by default. But in Xcode 15 is now set to YES. Change it back to NO.

This is also documented in the README already. Would be cool if people could confirm this is the right advice.

**Comment by lucaszischka** [comment]
Hey @SimplyDanny,
yes this solution indeed fixed the issue.

Greetings from Munich,
Lucas :)

**Comment by daljeet16** [comment]
I am using Xcode 15.2
Facing same issue while building on Jenkins machine: Here is the error:
The following build commands failed:

PhaseScriptExecution Swiftlint 
/Users/administrator/.jenkins/workspace/derivedData/Build/Intermediates.noindex/ArchiveIntermediates//Script-8571282F2B96E3BA00CF1389.sh 
(1 failure)

No Luck!
