### ISSUE TITLE
Allow '_' both in variable names and type names

### ISSUE THREAD

**Issue by frogcjn** [realm/SwiftLint#628]
Allow '_' both in variable names and type names.

for example: "class _BaseVC" for speical private type, and 'var rx_disposeBag' for using other frameworks (e.g. RxSwift).

**Comment by janekp** [comment]
I'd argue that there should be a general prefix rule for non-public variables/types. 3 most common ones are: "_", "m" and "m_". Many, including myself prefer this style, because it can be used in different languages (Objective-C, C++) and allows to safely omit self/this: "m_x = x" instead of "this.x = x".

Underscore prefix style can be seen in Apple libraries too: https://github.com/apple/swift-corelibs-foundation/tree/master/Foundation

**Comment by marcelofabri** [comment]
This was implemented in #1444

**Comment by sandeepbol** [comment]
I want to use _ only as prefix or suffix. How can I achieve that?

**Comment by jpsim** [comment]
You can only allow or disallow _ as a character anywhere in the name, not specifically as a prefix or suffix. That would be a reasonable configuration change for the rule though.
