### ISSUE TITLE
Support `filePrivate` for Private Unit Test Rule in Swift 3

### ISSUE THREAD

**Issue by cfilipov** [realm/SwiftLint#781]
#761 has been merged which adds a rule to detect private XCTests (which XCTest will silently not skip). This issue is to serve as a reminder that this rule should be updated when Swift 3 support is added because `filePrivate` has the same effect as `private` on unit tests.

**Comment by bdbergeron** [comment]
Any update on `fileprivate` support? I'd like to enable some opt-in rules such as `private_outlet` that currently give me warnings.

**Comment by cfilipov** [comment]
@bdbergeron I don't know if it's possible for SwiftLint to lint Swift < 3.x sources without itself being Swift 3 (which as far as I can tell it is not yet). In any case, I can probably guess at what the AST keys will be but unless I can run/debug and unit test against Swift 3 I don't see much point. I'm waiting for SwiftLint itself to move to Swift 3 before I can update this rule. There are a number of dependencies that would probably also need to update to Swift 3 before this project ([SourceKitten](https://github.com/jpsim/SourceKitten) being the most relevant).

**Comment by cfilipov** [comment]
@bdbergeron By the way, can you elaborate on what you mean about `private_outlet`? I can't imagine any case where you would want IBOutlets in unit tests. Are you getting false positives on private outlets? If that's the case, that might be my fault and that [issue](https://github.com/realm/SwiftLint/issues/786) is now fixed but hasn't been cut into a release yet (though I would expect that to only occur on *IBActions* and only when the action's name begins with *test*).

**Comment by jpsim** [comment]
Sorry for my absence @cfilipov. Slowly trying to work through my backlog of SwiftLint notifications 😅 .

> I don't know if it's possible for SwiftLint to lint Swift < 3.x sources without itself being Swift 3 (which as far as I can tell it is not yet)

Yes! The Swift version used to build SwiftLint is unrelated to the versions of Swift it can lint! That's because SourceKit is dynamically _found_ and _linked_. SwiftLint looks for a Swift toolchain in the following order:

* `$XCODE_DEFAULT_TOOLCHAIN_OVERRIDE`
* `$TOOLCHAIN_DIR`
* `xcrun -find swift`
* `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
* `/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
* `~/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
* `~/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`

> There are a number of dependencies that would probably also need to update to Swift 3 before this project

SourceKitten has supported Swift 3 essentially since day one, thanks to the same runtime linking mechanism as above, even though its codebase itself was only converted to Swift 3 [a few weeks ago](https://github.com/jpsim/SourceKitten/releases/tag/0.15.0).

No other dependencies interact with SourceKit, so nothing needs to be updated.

---

I think the "only" things that need to be changed to support `fileprivate` and `open` ACL keywords is to add them to the `AccessControlLevel` enum in [MissingDocsRule.swift](https://github.com/realm/SwiftLint/blob/0.13.0/Source/SwiftLintFramework/Rules/MissingDocsRule.swift#L56-L77) and adapt rules that would be affected. This can be done now, without having to update any dependencies.
