### ISSUE TITLE
Plans for Swift 3

### ISSUE THREAD

**Issue by cfilipov** [realm/SwiftLint#816]
I searched and found a number of issues that mention Swift 3, but nothing specifically about this project as a whole, forgive me if this has already been brought up. A recent comment on #781 has got me thinking about Swift 3 support and how it will work with SwiftLint.
1. Are there plans to update this project to Swift 3 (the source code itself)? 
   1. Of course this requires the dependencies be updated.
   2. Is this even necessary for linting Swift 3 code? I assume yes.
2. Can/will SwiftLint handle multiple versions of Swift?
   1. It's likely people will have multiple projects at various stages of migration, but only a single installation of SwiftLint.
   2. One option would be for Swift 2.x SwiftLint to ignore Swift 3.x and Swift 3.x SwiftLint to treat all Swift 2.x as a rule violation (now that Swift 3 is released).
   3. Although the majority of breaking changes are behind us, there is still the possibility that new versions of Swift can introduce or remove features that result in lint errors. It would be helpful if SwiftLint had at least some rudimentary handling of multiple Swift versions.
3. What happens when the current version of SwiftLint is run on a Swift 3 project? False positives? Does it know to ignore these files? 

I think these things should be mentioned in the README. _I am particularly concerned about those of us who have SwiftLint as part of their CI process and using it in git hooks_. Once people start updating their projects to Swift 3 or updating to a new SwiftLint with older projects things should be handled as gracefully as possible.

**Comment by Reedyuk** [comment]
I think it makes sense that the `.swiftlint` file, determines the version of swift the project is using, that way it would work fine on CI's.

**Comment by norio-nomura** [comment]
SourceKitten can use `sourcekitd.framework` from Swift toolchains both of 2.x and 3.0.
So basically, we don't need migrating SwiftLint itself to Swift 3.0 for supporting lints Swift 3.0 codes.

**Comment by norio-nomura** [comment]
But, we may need to create testing method on both of Swift 2.x and Swift 3.0, if we would support both of them.
If we would not support both of Swift 2.x and 3.0 simultaneously, users who needs both of them may be required to install multiple version of SwiftLint.

**Comment by cfilipov** [comment]
So you are saying each rule could support multiple versions of Swift by implementing `validateSwift2_2File`, `validateSwift2_3File`, `validateSwift3_0File`etc..?

**Comment by norio-nomura** [comment]
Yes.
We can detect version of Swift by using such as #703, and run rules selected by that.

I guess we would be able to support versions of Swift that supported by single Xcode version, e.g. Swift 2.3 and 3.0 on Xcode 8.

**Comment by SerenadeX** [comment]
One issue I am having is updating an existing installation of SwiftLint while Xcode 8 is installed.  It won't work with `brew` as it has to compile it after cloning it down.  Any plans on making it work in at least Swift 2.3 so it can compile on install with Xcode 8?

**Comment by norio-nomura** [comment]
`master` branch is compatible with swift 2.3, but not yet released.
On Sierra with Xcode 8, please try `brew install --HEAD swiftlint` for installing SwiftLint.

**Comment by Alak** [comment]
any news about swift 3 support ?

**Comment by norio-nomura** [comment]
I think most rules are compatible with Swift 3 other than `missing_docs` and `valid_docs`.
Migrating SwiftLint itself to Swift 3 is tracking on https://github.com/realm/SwiftLint/pull/832

**Comment by jpsim** [comment]
One thing to keep in mind is that the version of Swift used to _build_ SwiftLint does not impact which versions of Swift can be linted or corrected by SwiftLint.

That's because SourceKit is dynamically found and linked at runtime, based on a hierarchy of search locations (see [How is SourceKit resolved?](https://github.com/jpsim/SourceKitten#how-is-sourcekit-resolved)).

SourceKit's API is fairly stable in practice, which makes it possible for a version of SwiftLint compiled with Swift 2.x to successfully lint or correct a codebase written with Swift 3.0.

However, Apple makes no guarantees about this and reserves the right to change things drastically with no warning or reason.

There are rare times where SourceKit does change in ways that affect SwiftLint, the removal of the `__raw_doc_comment` attribute (#728/[SR-2487](https://bugs.swift.org/browse/SR-2487)) comes to mind as an example of this.

So when @Alak asks "any news about swift 3 support ?", well SwiftLint has supported it automatically as soon as the Swift 3 betas came out.

If there are specific issues with Swift 3 (such as #728), we ask that you be diligent about thoroughly reporting these as GitHub Issues, which we'll then be able to address on an individual basis.

**Comment by Alak** [comment]
Great answer, I will try it next week :). Thank you

**Comment by marcelofabri** [comment]
Closing this now since SwiftLint was migrated to Swift 3 in #832 and there're specific issues for Swift 3 bugs/enhancements (such as #728).
