### ISSUE TITLE
Setup Danger?

### ISSUE THREAD

**Issue by marcelofabri** [realm/SwiftLint#843]
[People](https://github.com/realm/SwiftLint/pull/842#issuecomment-253991177) seems to forget about adding an entry to CHANGELOG. We could add [Danger](http://danger.systems) to validate that automatically.

We could even borrow [CocoaPods's Dangerfile](https://github.com/CocoaPods/CocoaPods/blob/master/Dangerfile#L18-L32).

**Comment by jpsim** [comment]
I'm in favor of doing this and would welcome a PR adding Danger checks. But this isn't something I plan on doing myself since the last few times I've tried doing that, I ended up disabling it due to issues getting it to work consistently.

**Comment by masters3d** [comment]
I've also experience danger braking the build when the script crashers. 
The way I side stepped the issue was by making Danger an after success script. 
The advantage is that Danger will never brake the build but then if danger brakes it will be just silence. I'd be happy to set that up with the above checks mentioned.  
Could we use the same bot as Jazzy?  (DangerCI new token? or the same?)
