### ISSUE TITLE
Unable to build SwiftLint

### ISSUE THREAD

**Issue by prabodhprakash** [realm/SwiftLint#927]
I cloned the repo and when I do `carthage update` I get the following

`ld: warning: directory not found for option '-L/Users/prabodhprakash/Library/Developer/Xcode/DerivedData/Yams-dytaixnmmqunhyfyzjdmadzjouyd/Build/Intermediates/Yams.build/SymlinkLibs'`

`ld: warning: directory not found for option '-L/Users/prabodhprakash/Library/Developer/Xcode/DerivedData/SourceKitten-hdffnrcrupvfcmbwcmnsqwtacumz/Build/Intermediates/Yams.build/SymlinkLibs'`

Post which build in Xcode does not happen.

**Comment by jpsim** [comment]
SwiftLint isn't designed to build with the `carthage update` command. We document several installation methods in our README: https://github.com/realm/SwiftLint#installation

We do support updating the git submodules for our dependencies using `carthage update --no-build --use-submodules` however, which is why we have a Cartfile, but that doesn't build SwiftLint. It just updates the necessary dependencies.
